# PostgreSQL credentials for book-service database.

apiVersion: v1
kind: Secret
metadata:
  name: book-postgres-secret
  namespace: book-postgres
  labels:
    app.kubernetes.io/name:      book-postgres
    app.kubernetes.io/component: secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MXE4R0NsVzJuQUJt
  POSTGRES_DB: Ym9va19kYg==